version: "3"
services:
  symfony:
    build: apache-php-mysql
    ports:
      - 80:80
    volumes:
      - ./symfony:/var/www/symfony
      - ./apache-php-mysql/apache.conf:/etc/apache2/sites-enabled/000-default.conf
    working_dir: /var/www/symfony
    env_file:
      - .env
  composer:
    image: composer:latest
    working_dir: /var/www/symfony
    volumes:
      - ./symfony:/var/www/symfony
  mariadb:
    image: mariadb:10.3
    env_file:
      - .env
  redis:
    image: redis:4
    volumes:
      - redisdata:/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  elk:
    image: willdurand/elk
    ports:
      - 8080:80
    volumes:
      - ./elk/logstash:/etc/logstash
      - ./elk/logstash/patterns:/opt/logstash/patterns
      - ./symfony:/var/www/symfony
volumes:
  esdata:
    driver: local
  redisdata:
    driver: local